version: "3.9"
services:
  redis:
    container_name: redis_conatiner
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --loglevel warning
    volumes:
      - ./docker-volumes/cache:/data
  mongodb:
    container_name: mongodb_conatiner
    image: mongo:latest
    restart: always
    ports:
      - "27017:27107"
    volumes:
      - ./docker-volumes/data:/data/db
  mysql:
    container_name: mysql_conatiner
    image: mysql
    #  command: --default-authentication-plugin=mysql_native_password
    # This command changes the default authentication plugin for MySQL from
    #caching_sha2_password (which is the default in MySQL 8.0+) to mysql_native_password.

    restart: always
    environment:
      - MYSQL_USER=asif
      - MYSQL_DATABASE=asif
      - MYSQL_ROOT_PASSWORD=asif
      - MYSQL_PASSWORD=asif
    ports:
      - "3306:3306"
    volumes:
      - ./docker-volumes/mysql:/var/lib/mysql
postgres:
  container_name: postgres_conatiner
  image: postgres
  restart: always
  environment:
    - POSTGRES_USER=asif
    - POSTGRES_PASSWORD=asif
    - POSTGRES_DB=asif
  ports:
    - "5432:5432"
  volumes:
    - ./docker-volumes/postgres:/var/lib/postgres:/var/lib/postgressql
rabbitmq:
  container_name: rabbitmq_container
  image: rabbitmq:3.13-rc-management-alpine
  restart: always
  ports:
    #AMQP protocol port
    - "5672:5672"
    #Management UI
    - "15672:15672"
